# Generated by Django 5.1.7 on 2025-03-28 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('color_style', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='TalleAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TalleCalzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TalleIndumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('descuento', models.IntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('niños', 'Niños'), ('unisex', 'Unisex')], max_length=20)),
                ('tipo_producto', models.CharField(choices=[('indumentaria', 'Indumentaria'), ('calzado', 'Calzado'), ('accesorios', 'Accesorios')], default='indumentaria', max_length=20)),
                ('estado', models.CharField(blank=True, choices=[('novedades', 'Novedades'), ('destacados', 'Destacados'), ('sale', 'Sale')], max_length=20, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen_principal', models.ImageField(upload_to='fotos/')),
                ('imagen_secundaria_1', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('imagen_secundaria_2', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('imagen_secundaria_3', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoria')),
                ('colores', models.ManyToManyField(to='products.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marca')),
                ('talles_accesorios', models.ManyToManyField(blank=True, null=True, to='products.talleaccesorio')),
                ('talles_calzado', models.ManyToManyField(blank=True, null=True, to='products.tallecalzado')),
                ('talles_indumentaria', models.ManyToManyField(blank=True, null=True, to='products.talleindumentaria')),
            ],
        ),
    ]
