# Generated by Django 5.1.7 on 2025-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('indumentaria', 'Indumentaria'), ('calzado', 'Calzado'), ('accesorios', 'Accesorios')], max_length=20, null=True),
        ),
    ]
