# Generated by Django 5.1.7 on 2025-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(blank=True, to='products.color'),
        ),
    ]
