# Generated by Django 5.1.7 on 2025-04-30 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0003_alter_imagenproducto_options_remove_producto_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='talle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.talle'),
        ),
    ]
