# Generated by Django 5.1.7 on 2025-05-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_ciudad_pedido_codigo_postal_pedido_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario',
            new_name='user',
        ),
    ]
